import { ObjectType, Field, ID } from "type-graphql";
import { prop, getModelForClass } from "@typegoose/typegoose";

@ObjectType({ description: "Steps Of the Recipe" })
export class RecipeStep {
	@Field((_type) => ID)
	// Autogenerated key by Mongo. Graphql not nullable
	id?: string;

	@Field()
	@prop({ required: true })
	title!: string;

	@Field({ nullable: true })
	@prop()
	img?: string;

	@Field({ nullable: true })
	@prop()
	description?: string;
}

export interface RecipeStepInterface extends RecipeStep {}

export const RecipeStepModel = getModelForClass(RecipeStep);
