import { ObjectType, Field, ID } from "type-graphql";
import { prop, getModelForClass } from "@typegoose/typegoose";

@ObjectType({ description: "The categories of the recipes" })
export class RecipeCategory {
	@Field((_type) => ID)
	// Autogenerated key by Mongo. Graphql not nullable
	id?: string;

	@Field()
	@prop({ required: true, unique: true })
	title: string;
}

export const RecipeCategoryModel = getModelForClass(RecipeCategory);

export interface RecipeCategoryInterface extends RecipeCategory {}
